# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AutoUpdate

on:
  push:
    branches: [ "vue33" ]
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - 'LICENSE'
      - '.gitignore'
      - 'README.md' 
      - 'version.info' 
      - 'gameDataVersion'
  # schedule:
    # Runs "At every 5 minute." (see https://crontab.guru)
    # - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: gamedata update
      run: |
        python3 autoUpdate.py ${{ secrets.QQBOTTOKEN }} ${{ secrets.GITHUBTOKEN }}
        
    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto Update
        commit_user_name: ClosureBot
        commit_user_email: ${{ secrets.BOTEMAIL }}
        commit_author: ClosureBot <${{ secrets.BOTEMAIL }}>
